spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 #2h
    refreshTokenExpiration: 604800 #7d

  output:
    ansi:
      enabled: always
  main:
    banner-mode: console
  # In my railway deploy the profile is set to "prod"
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}