spring:
  data:
    redis:
      # Use host = localhost to use redis locally
      # or host = redis (docker service name) to use it with the docker container
      host: localhost
      port: 6379
      password: password
      timeout: 10s
  datasource:
    # To run locally with mysql use mysql url property and keep commented the another one
    # To run the app + db inside docker containers, use the docker url
    # Remember that database data defined in compose.yml should match with the datasource url data here
    # local mysql datasource url
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    # Docker mysql datasource url
    # url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
  main:
    banner-mode: console
websiteUrl: http://localhost:8080
management:
  endpoint:
    health:
      show-details: always   # in dev, everything can be shown
  endpoints:
    web:
      exposure:
        # Allowed actuator endpoints (whitelist)
        include: "*"