spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: password.123
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
  main:
    banner-mode: console
websiteUrl: http://localhost:4242