name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  build-test:
    name: Build & unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Repository checkout # Checkouts our repo to the runner
        uses: actions/checkout@v6
      - name: Set up Java 17 # Installs java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Show java & Maven
        run: |
          java -version
          ./mvnw -v
      - name: Run unit tests
        run: |
          ./mvnw -B -V test
      - name: Upload surefire reports # artifacts are saved and downloadable
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: surefire-reports
          path: target/surefire-reports/
          retention-days: 5
  integration-test:
    name: Integration tests (Testcontainers / Failsafe)
    runs-on: ubuntu-22.04
    needs: build-test # The previous job 'build-test' is needed
    steps:
      - name: Repository checkout # Checkouts our repo to the runner
        uses: actions/checkout@v6
      - name: Set up Java 17 # Installs java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      # verify executes integration tests (failsafe) and unit tests are skipped
      - name: Run integration tests (verify)
        run: |
          ./mvnw -B -V -DskipUnitTests=true verify
        timeout-minutes: 40
      - name: Upload failsafe reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: failsafe-reports
          path: target/failsafe-reports/
          retention-days: 5